[package]
name = "tuisic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
mpv = "0.2.3"
ratatui = "0.26.1"
xdg-user = "0.2.1"
